### ISSUE TITLE
Add support for Forwarded header

### ISSUE THREAD

**Issue by niklasholm** [turboMaCk/koa-sslify#25]
The `Forwarded` header is standardized to replace the `X-Forwarded-*` headers and should be supported as well.

* [Forwarded | MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Forwarded)

**Comment by turboMaCk** [comment]
@niklasholm I decided to redesign API of the lib in order to make support for various strategies more scalable (related also to https://github.com/turboMaCk/koa-sslify/pull/24 cc @shlomisas).

Newly released version 3.0.0 now uses resolver functions and contains an implementation of a resolver for Forwarded header as well.

See updated documentation (README) and changelog for more details.

happy new year!
