### ISSUE TITLE
Redirect https://domain.com to https://www.domain.com

### ISSUE THREAD

**Issue by alphanso** [turboMaCk/koa-sslify#7]
Hi,

Its important for SEO to have only one active subdomain. Is it possible to provide this functionality as well.

Regards
Rishabh

**Comment by turboMaCk** [comment]
Hi Rishabh,
I think this is out of scope of this middleware. You can set `https://www.domain.com` to be target while redirecting from unsecure `http://domain.com` but when connection is classified as secure, this middleware is simply skipped which is right way I think. Anyway I'll think about this a little bit more and let you know.

**Comment by turboMaCk** [comment]
I was thinking about this for a while but to be honest the only feeling I have is that it will be maybe better to remove even `hostname` from options. I don't mean that adding logic for redirect would be any hard task, but I want to keep this thing as simple as possible. For now if connection is classified as `secure` middleware is immediately skipped. This makes it really easy to reason about. Adding some additional redirection logic brings some unnecessary and not obvious complexity to every app using this. I like to thing about is as about blackbox – nobody using this needs to know any of implementation details and read much documentation. It's pretty obvious what this does and how to use it. To me it's not obvious that something like this can cause some redirection from one secure connection to another.

**Comment by simlmx** [comment]
I think this should do the trick!

```javascript
hostToRedirectTo = 'yourhost.com'

app.use(async (ctx, next) => {
  if (ctx.request.header.host !== hostToRedirectTo) {
    ctx.status = 301;
    ctx.redirect("http://" + hostToRedirectTo + ctx.request.url);
    return;
  }
  await next();
});

// your normal sslify middleware init
app.use(sslify({ resolver }));

```

**Comment by turboMaCk** [comment]
I think it might be worth clarifying few I feel. First of all this middleware essentially does 2 things which depend on each other

1. Detect if connection is secure (https) or not (using given resolver)
2. If connection is not secured, redirect to secure connection is performed.

So we already perform redirect for all insecure host names and for those we can redirect from one domain to another like.

```
http://non-existant.domain.com -> https://correct.domain.com
```

This can be already done using `host` property on configuration object.

What this middleware does **not** do is perform any sort of redirect for secure connection. I think this is reasonable promise to make - we do stuff only for insecure request and don't touch anything secure at all.

This means that this is not done:

```
https://non-existant.domain.com -> https://correct.domain.com
```

Since the request to `non-existant` subdomain is secure, we don't touch it.

We allow to specify host to redirect to for insecure requests though so one can easily avoid multiple unnecessary redirects being performed. So putting this all together this is how implementation that grantees there won't be more than single redirect needed to get user to the correct domain would look like:


```js
host = 'yourhost.com'

// Redirect insecure requests
app.use(sslify({
  resolver,
  host // make sure we redirect to the correct host right away
}));

// Redirect secure requests to right domain
app.use(async (ctx, next) => {
  if (ctx.request.header.host !== host) {
    ctx.status = 301;
    ctx.redirect("https://" + host + ctx.request.url);
    return;
  }
  await next();
});
```

There is one more thing to consider when implementing redirect though. Usually one wants to redirect only `GET` and `HEAD` since redirecting other requests might be problematic. For these it's better to simply return `405` error.

I'm going to reopen this issue in case this needs some additional clarification or perhaps update in documentation.

**Comment by simlmx** [comment]
Thanks for the quick reply!

If I change the redirect to `https://` in my first snippet though, then the two solutions would be equivalent (maximum of one redirect), no?

**Comment by turboMaCk** [comment]
yes essentially. except that koa-sslify doesn't redirect on all methods etc.

**Comment by turboMaCk** [comment]
thanks to @newhouse there will be version that addresses https://github.com/turboMaCk/koa-sslify/issues/40 out soon. I think this might also resolve address things raised within this thread as the change adds a bit more flexibility to the redirection logic which I think might resolve use-cases from this thread as well. Just be aware that this will be a major version bump with breaking change.

**Comment by turboMaCk** [comment]
new version (5.0.0) was just released replacing the hostname setting from string to function from one string to another. I think this should be sufficient even for cases from this issue - closing.
