### ISSUE TITLE
why is it adding the port in the url ?

### ISSUE THREAD

**Issue by MathRobin** [turboMaCk/koa-sslify#8]
Hi !

I'm using this great koa plugin but I have a question. Why does he add the port in the https generated url ?

For example, for my website, it redirects this page

    http://www.matosmaison.fr/avis/ventilateurs/rowenta-vu4110f0

to

    https://www.matosmaison.fr:443/avis/ventilateurs/rowenta-vu4110f0

Nothing wrong but some seo crawl tools say we are in duplicate content case cause of difference between the url with or without the 443 port inside.

**Comment by turboMaCk** [comment]
Hello @MathRobin !

Port 443 is default for HTTPS protocol but with this plugin it works like any other port of choice. This means that port is added to url even it's default 443 (which can be automatically resolves by every browser).

Anyway I think that it makes sense to skip port from url if its `403`. Are you interested in submitting PR for this since you point it out? Otherwise I can do it myself.

Thanks for this issue.

Marek

**Comment by MathRobin** [comment]
Yes I will make a PR with port optional, with 443 by default

**Comment by turboMaCk** [comment]
I think we can add function `portToUrlString` which takes a number and returns string version like this:

```js
function portToUrlString(port) {
  return port === 443 ? '' : port + '';
}
```

**Comment by MathRobin** [comment]
PR done. Didn't see your message before finishing it. Sorry

**Comment by turboMaCk** [comment]
@MathRobin No problem. Let's move further discussion in the PR itself;)
